name: Vehicle Server CI
on:
  - push
  - pull_request
jobs:
  verification-ci-vehicle-server:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      
      - name: Test
        run: npm run test

      - name: Install Dependencies
        run: npm install

      - name: Check Node Version
        run: node --version

      - name: Build application
        run: npm run build
      
      - name: Run Lint
        run: npm run lint

      - name: Test CLI
        run: npm run build && node dist/cli.js --help